# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fileWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(465, 669)
        self.top_label_2 = QtWidgets.QLabel(Form)
        self.top_label_2.setGeometry(QtCore.QRect(0, 0, 551, 251))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(20)
        self.top_label_2.setFont(font)
        self.top_label_2.setStyleSheet("background:transparent;")
        self.top_label_2.setObjectName("top_label_2")
        self.top_label = QtWidgets.QLabel(Form)
        self.top_label.setGeometry(QtCore.QRect(0, 0, 581, 251))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(20)
        self.top_label.setFont(font)
        self.top_label.setStyleSheet("background:red;")
        self.top_label.setObjectName("top_label")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-20, 342, 81, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(77, 332, 291, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(380, 332, 71, 41))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(77, 400, 291, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 402, 71, 41))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(-15, 412, 81, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(77, 470, 291, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(380, 472, 71, 41))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(11)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(-16, 480, 81, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 560, 141, 51))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(11)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(280, 560, 141, 51))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(11)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.clsBtn = QtWidgets.QPushButton(Form)
        self.clsBtn.setGeometry(QtCore.QRect(439, -2, 28, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.clsBtn.setFont(font)
        self.clsBtn.setObjectName("clsBtn")
        self.top_label.raise_()
        self.top_label_2.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.pushButton.raise_()
        self.lineEdit_2.raise_()
        self.pushButton_2.raise_()
        self.label_2.raise_()
        self.lineEdit_3.raise_()
        self.pushButton_3.raise_()
        self.label_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.clsBtn.raise_()

        self.retranslateUi(Form)
        self.pushButton_3.clicked.connect(self.lineEdit_3.clear)
        self.pushButton_3.clicked.connect(self.lineEdit_2.clear)
        self.pushButton_3.clicked.connect(self.lineEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FILE_SMS4"))
        self.top_label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:24pt; color:#ffffff;\">&nbsp;&nbsp;FILE</span></p><p><span style=\" font-size:24pt; color:#ffffff;\">&nbsp;&nbsp;SMS4</span></p></body></html>"))
        self.top_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:24pt; color:#ffffff;\">  FILE</span></p><p><span style=\" font-size:24pt; color:#ffffff;\">  SMS4</span></p></body></html>"))
        self.label.setText(_translate("Form", "File"))
        self.pushButton.setText(_translate("Form", "Choos.."))
        self.pushButton_2.setText(_translate("Form", "Choos.."))
        self.label_2.setText(_translate("Form", "SaveAs"))
        self.pushButton_3.setText(_translate("Form", "Clean"))
        self.label_3.setText(_translate("Form", "Key"))
        self.pushButton_4.setText(_translate("Form", "EnCrypt"))
        self.pushButton_5.setText(_translate("Form", "DeCrypt"))
        self.clsBtn.setText(_translate("Form", "×"))

