# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'normalWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_normal_sms(object):
    def setupUi(self, normal_sms):
        normal_sms.setObjectName("normal_sms")
        normal_sms.resize(835, 503)
        self.left_label = QtWidgets.QLabel(normal_sms)
        self.left_label.setGeometry(QtCore.QRect(0, -10, 221, 541))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(20)
        self.left_label.setFont(font)
        self.left_label.setStyleSheet("background:red;")
        self.left_label.setObjectName("left_label")
        self.msgEdit = QtWidgets.QTextEdit(normal_sms)
        self.msgEdit.setGeometry(QtCore.QRect(310, 70, 501, 131))
        self.msgEdit.setObjectName("msgEdit")
        self.cyrEdit = QtWidgets.QTextEdit(normal_sms)
        self.cyrEdit.setGeometry(QtCore.QRect(310, 240, 501, 131))
        self.cyrEdit.setObjectName("cyrEdit")
        self.msgLabel = QtWidgets.QLabel(normal_sms)
        self.msgLabel.setGeometry(QtCore.QRect(227, 120, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.msgLabel.setFont(font)
        self.msgLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.msgLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.msgLabel.setObjectName("msgLabel")
        self.cyrLabel = QtWidgets.QLabel(normal_sms)
        self.cyrLabel.setGeometry(QtCore.QRect(226, 293, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.cyrLabel.setFont(font)
        self.cyrLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cyrLabel.setObjectName("cyrLabel")
        self.encBtn = QtWidgets.QPushButton(normal_sms)
        self.encBtn.setGeometry(QtCore.QRect(580, 410, 71, 41))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(11)
        self.encBtn.setFont(font)
        self.encBtn.setObjectName("encBtn")
        self.decBtn = QtWidgets.QPushButton(normal_sms)
        self.decBtn.setGeometry(QtCore.QRect(660, 410, 71, 41))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(11)
        self.decBtn.setFont(font)
        self.decBtn.setObjectName("decBtn")
        self.keyEdit = QtWidgets.QLineEdit(normal_sms)
        self.keyEdit.setGeometry(QtCore.QRect(310, 410, 251, 41))
        self.keyEdit.setObjectName("keyEdit")
        self.keyLabel = QtWidgets.QLabel(normal_sms)
        self.keyLabel.setGeometry(QtCore.QRect(225, 409, 81, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.keyLabel.setFont(font)
        self.keyLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.keyLabel.setObjectName("keyLabel")
        self.clnBtn = QtWidgets.QPushButton(normal_sms)
        self.clnBtn.setGeometry(QtCore.QRect(740, 410, 71, 41))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(11)
        self.clnBtn.setFont(font)
        self.clnBtn.setObjectName("clnBtn")
        self.clsBtn = QtWidgets.QPushButton(normal_sms)
        self.clsBtn.setGeometry(QtCore.QRect(809, -3, 28, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.clsBtn.setFont(font)
        self.clsBtn.setObjectName("clsBtn")
        self.left_label_2 = QtWidgets.QLabel(normal_sms)
        self.left_label_2.setGeometry(QtCore.QRect(0, -20, 221, 541))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(20)
        self.left_label_2.setFont(font)
        self.left_label_2.setStyleSheet("background:transparent;")
        self.left_label_2.setObjectName("left_label_2")

        self.retranslateUi(normal_sms)
        self.clnBtn.clicked.connect(self.keyEdit.clear)
        self.clnBtn.clicked.connect(self.cyrEdit.clear)
        self.clnBtn.clicked.connect(self.msgEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(normal_sms)

    def retranslateUi(self, normal_sms):
        _translate = QtCore.QCoreApplication.translate
        normal_sms.setWindowTitle(_translate("normal_sms", "NORMAL_SMS4"))
        self.left_label.setText(_translate("normal_sms", "<html><head/><body><p><span style=\" font-size:24pt; color:#ffffff;\">  NORMAL</span></p><p><span style=\" font-size:24pt; color:#ffffff;\">  SMS4</span></p></body></html>"))
        self.msgLabel.setText(_translate("normal_sms", "Message"))
        self.cyrLabel.setText(_translate("normal_sms", "Cypher"))
        self.encBtn.setText(_translate("normal_sms", "Enc"))
        self.decBtn.setText(_translate("normal_sms", "Dec"))
        self.keyLabel.setText(_translate("normal_sms", "Key"))
        self.clnBtn.setText(_translate("normal_sms", "Clean"))
        self.clsBtn.setText(_translate("normal_sms", "×"))
        self.left_label_2.setText(_translate("normal_sms", "<html><head/><body><p><span style=\" font-size:24pt; color:#ffffff;\">  NORMAL</span></p><p><span style=\" font-size:24pt; color:#ffffff;\">  SMS4</span></p></body></html>"))

